# Generated by Django 5.2.5 on 2025-12-03 18:58

import core.models
import core.validators
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('food_category', models.CharField(choices=[('fruits', 'Fruits'), ('vegetables', 'Vegetables'), ('grains', 'Grains & Bread'), ('protein', 'Protein (Meat/Fish)'), ('dairy', 'Dairy'), ('pantry', 'Pantry Items'), ('prepared', 'Prepared Meals'), ('beverages', 'Beverages'), ('other', 'Other')], db_index=True, max_length=20)),
                ('description', models.TextField()),
                ('quantity', models.CharField(max_length=100)),
                ('expiry_datetime', models.DateTimeField(db_index=True)),
                ('pickup_start', models.DateTimeField()),
                ('pickup_end', models.DateTimeField()),
                ('pickup_location', models.CharField(help_text='Full address or meeting point', max_length=255)),
                ('status', models.CharField(choices=[('available', 'Available'), ('claimed', 'Claimed'), ('completed', 'Completed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='available', max_length=20)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.models.donation_image_path, validators=[core.validators.validate_image_size])),
                ('dietary_tags', models.JSONField(blank=True, default=list, validators=[core.validators.validate_dietary_tags])),
                ('estimated_calories', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('nutrition_score', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('ingredients_list', models.TextField(blank=True)),
                ('allergen_info', models.TextField(blank=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations_given', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'donations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'email_verifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('donation_claimed', 'Donation Claimed'), ('donation_completed', 'Donation Completed'), ('new_donation', 'New Donation'), ('rating_received', 'Rating Received'), ('system', 'System Notification')], db_index=True, max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('related_url', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('related_donation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.donation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, max_length=500)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='core.donation')),
                ('rated_user', models.ForeignKey(help_text='User being rated', on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to=settings.AUTH_USER_MODEL)),
                ('rating_user', models.ForeignKey(help_text='User who gave the rating', on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ratings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_type', models.CharField(choices=[('donor', 'Donor'), ('recipient', 'Recipient')], db_index=True, max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, validators=[core.validators.validate_phone_number])),
                ('location', models.CharField(blank=True, help_text="City or neighborhood (e.g., 'Westlands, Nairobi')", max_length=255)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=core.models.user_profile_picture_path, validators=[core.validators.validate_image_size])),
                ('dietary_restrictions', models.JSONField(blank=True, default=list, help_text="List of dietary restrictions (e.g., ['vegetarian', 'gluten-free'])", validators=[core.validators.validate_dietary_tags])),
                ('email_verified', models.BooleanField(default=False)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('total_ratings', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['status', 'expiry_datetime'], name='donations_status_1caa89_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['donor', 'status'], name='donations_donor_i_9c0085_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['recipient', 'status'], name='donations_recipie_f4cf3b_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['food_category'], name='donations_food_ca_76f4d6_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', '-created_at'], name='notificatio_user_id_c4e471_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['rated_user', 'rating'], name='ratings_rated_u_5255d1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('donation', 'rating_user', 'rated_user')},
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user_type', 'email_verified'], name='user_profil_user_ty_3ca939_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['average_rating'], name='user_profil_average_9be568_idx'),
        ),
    ]
