# Generated by Django 5.2.5 on 2025-09-22 18:47

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_type', models.CharField(choices=[('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('dairy', 'Dairy'), ('bakery', 'Bakery'), ('cooked', 'Cooked Food'), ('other', 'Other')], max_length=50)),
                ('quantity', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('expiry_date', models.DateTimeField(default=datetime.datetime(2025, 9, 29, 18, 47, 15, 606841, tzinfo=datetime.timezone.utc), help_text='Food expiry date')),
                ('pickup_time', models.DateTimeField(default=datetime.datetime(2025, 9, 23, 18, 47, 15, 606912, tzinfo=datetime.timezone.utc))),
                ('pickup_deadline', models.DateTimeField(default=datetime.datetime(2025, 9, 24, 18, 47, 15, 606956, tzinfo=datetime.timezone.utc), help_text='Last pickup date')),
                ('location', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('available', 'Available'), ('claimed', 'Claimed'), ('completed', 'Completed'), ('expired', 'Expired')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_donations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('donor', 'Donor'), ('recipient', 'Recipient')], default='donor', max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
