# Generated by Django 6.0 on 2026-02-06 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='nutrition_score',
        ),
        migrations.AlterField(
            model_name='notification',
            name='related_donation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='core.donation'),
        ),
    ]
