# Generated by Django 5.2.5 on 2025-12-02 18:52

import core.models
import core.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='donation',
            name='donations_food_ca_cb6351_idx',
        ),
        migrations.RemoveIndex(
            model_name='rating',
            name='ratings_rated_u_de708f_idx',
        ),
        migrations.RemoveIndex(
            model_name='userprofile',
            name='user_profil_last_ac_f0c215_idx',
        ),
        migrations.RenameField(
            model_name='emailverification',
            old_name='is_verified',
            new_name='is_used',
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='emailverification',
            name='verified_at',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='read_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_active',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_verified',
        ),
        migrations.AlterField(
            model_name='donation',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='donation',
            name='estimated_calories',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='donation',
            name='food_category',
            field=models.CharField(choices=[('fruits', 'Fruits'), ('vegetables', 'Vegetables'), ('grains', 'Grains & Bread'), ('protein', 'Protein (Meat/Fish)'), ('dairy', 'Dairy'), ('pantry', 'Pantry Items'), ('prepared', 'Prepared Meals'), ('beverages', 'Beverages'), ('other', 'Other')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='donation',
            name='pickup_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='donation',
            name='pickup_location',
            field=models.CharField(help_text='Full address or meeting point', max_length=255),
        ),
        migrations.AlterField(
            model_name='donation',
            name='pickup_start',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='donation',
            name='quantity',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='donation',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('claimed', 'Claimed'), ('completed', 'Completed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='expires_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='token',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('donation_claimed', 'Donation Claimed'), ('donation_completed', 'Donation Completed'), ('new_donation', 'New Donation'), ('rating_received', 'Rating Received'), ('system', 'System Notification')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rated_user',
            field=models.ForeignKey(help_text='User being rated', on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating_user',
            field=models.ForeignKey(help_text='User who gave the rating', on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dietary_restrictions',
            field=models.JSONField(blank=True, default=list, help_text="List of dietary restrictions (e.g., ['vegetarian', 'gluten-free'])", validators=[core.validators.validate_dietary_tags]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, help_text="City or neighborhood (e.g., 'Westlands, Nairobi')", max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, validators=[core.validators.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.user_profile_picture_path, validators=[core.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='total_ratings',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('donor', 'Donor'), ('recipient', 'Recipient')], db_index=True, max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('donation', 'rating_user', 'rated_user')},
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['recipient', 'status'], name='donations_recipie_f4cf3b_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['food_category'], name='donations_food_ca_76f4d6_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['rated_user', 'rating'], name='ratings_rated_u_5255d1_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['average_rating'], name='user_profil_average_9be568_idx'),
        ),
    ]
