# Generated by Django 5.2.5 on 2025-09-22 18:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 29, 18, 48, 17, 751964, tzinfo=datetime.timezone.utc), help_text='Food expiry date'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='pickup_deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 24, 18, 48, 17, 752093, tzinfo=datetime.timezone.utc), help_text='Last pickup date'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='pickup_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 23, 18, 48, 17, 752032, tzinfo=datetime.timezone.utc)),
        ),
    ]
