# Generated by Django 6.0 on 2026-02-06 11:49

import core.choices
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_donation_nutrition_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='pickup_details',
            field=models.CharField(blank=True, help_text='Optional: Specific address, landmark, or meeting point within the zone', max_length=255),
        ),
        migrations.AlterField(
            model_name='donation',
            name='pickup_location',
            field=models.CharField(choices=[('', 'Select your location...'), ('cbd', 'Nairobi CBD'), ('upperhill', 'Upper Hill'), ('ngara', 'Ngara'), ('parklands', 'Parklands'), ('westlands', 'Westlands'), ('kileleshwa', 'Kileleshwa'), ('kilimani', 'Kilimani'), ('lavington', 'Lavington'), ('hurlingham', 'Hurlingham'), ('runda', 'Runda'), ('muthaiga', 'Muthaiga'), ('gigiri', 'Gigiri'), ('spring_valley', 'Spring Valley'), ('southb', 'South B'), ('southc', 'South C'), ('langata', 'Langata'), ('karen', 'Karen'), ('imara', 'Imara Daima'), ('nyayo', 'Nyayo Estate'), ('madaraka', 'Madaraka'), ('eastleigh', 'Eastleigh'), ('buruburu', 'Buruburu'), ('donholm', 'Donholm'), ('umoja', 'Umoja'), ('embakasi', 'Embakasi'), ('pipeline', 'Pipeline'), ('kayole', 'Kayole'), ('komarock', 'Komarock'), ('roysambu', 'Roysambu'), ('kasarani', 'Kasarani'), ('kahawa_west', 'Kahawa West'), ('kahawa_sukari', 'Kahawa Sukari'), ('zimmerman', 'Zimmerman'), ('thika_rd', 'Thika Road'), ('ruaraka', 'Ruaraka'), ('ruaka', 'Ruaka'), ('kitisuru', 'Kitisuru'), ('runda', 'Runda'), ('membley', 'Membley'), ('thindigua', 'Thindigua'), ('juja', 'Juja'), ('syokimau', 'Syokimau'), ('ongata_rongai', 'Ongata Rongai'), ('kitengela', 'Kitengela'), ('ngong', 'Ngong'), ('kiserian', 'Kiserian'), ('mombasa', 'Mombasa'), ('malindi', 'Malindi'), ('kilifi', 'Kilifi'), ('lamu', 'Lamu'), ('watamu', 'Watamu'), ('kisumu', 'Kisumu'), ('eldoret', 'Eldoret'), ('kakamega', 'Kakamega'), ('bungoma', 'Bungoma'), ('kitale', 'Kitale'), ('nakuru', 'Nakuru'), ('thika', 'Thika Town'), ('nyeri', 'Nyeri'), ('nanyuki', 'Nanyuki'), ('naivasha', 'Naivasha'), ("murang'a", "Murang'a"), ('machakos', 'Machakos'), ('embu', 'Embu'), ('meru', 'Meru'), ('garissa', 'Garissa'), ('narok', 'Narok'), ('kericho', 'Kericho'), ('bomet', 'Bomet'), ('kisii', 'Kisii'), ('homa_bay', 'Homa Bay'), ('migori', 'Migori'), ('other', 'Other Location (Not Listed)')], db_index=True, help_text='Select pickup zone/neighborhood', max_length=50, validators=[core.choices.validate_location_choice]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, choices=[('', 'Select your location...'), ('cbd', 'Nairobi CBD'), ('upperhill', 'Upper Hill'), ('ngara', 'Ngara'), ('parklands', 'Parklands'), ('westlands', 'Westlands'), ('kileleshwa', 'Kileleshwa'), ('kilimani', 'Kilimani'), ('lavington', 'Lavington'), ('hurlingham', 'Hurlingham'), ('runda', 'Runda'), ('muthaiga', 'Muthaiga'), ('gigiri', 'Gigiri'), ('spring_valley', 'Spring Valley'), ('southb', 'South B'), ('southc', 'South C'), ('langata', 'Langata'), ('karen', 'Karen'), ('imara', 'Imara Daima'), ('nyayo', 'Nyayo Estate'), ('madaraka', 'Madaraka'), ('eastleigh', 'Eastleigh'), ('buruburu', 'Buruburu'), ('donholm', 'Donholm'), ('umoja', 'Umoja'), ('embakasi', 'Embakasi'), ('pipeline', 'Pipeline'), ('kayole', 'Kayole'), ('komarock', 'Komarock'), ('roysambu', 'Roysambu'), ('kasarani', 'Kasarani'), ('kahawa_west', 'Kahawa West'), ('kahawa_sukari', 'Kahawa Sukari'), ('zimmerman', 'Zimmerman'), ('thika_rd', 'Thika Road'), ('ruaraka', 'Ruaraka'), ('ruaka', 'Ruaka'), ('kitisuru', 'Kitisuru'), ('runda', 'Runda'), ('membley', 'Membley'), ('thindigua', 'Thindigua'), ('juja', 'Juja'), ('syokimau', 'Syokimau'), ('ongata_rongai', 'Ongata Rongai'), ('kitengela', 'Kitengela'), ('ngong', 'Ngong'), ('kiserian', 'Kiserian'), ('mombasa', 'Mombasa'), ('malindi', 'Malindi'), ('kilifi', 'Kilifi'), ('lamu', 'Lamu'), ('watamu', 'Watamu'), ('kisumu', 'Kisumu'), ('eldoret', 'Eldoret'), ('kakamega', 'Kakamega'), ('bungoma', 'Bungoma'), ('kitale', 'Kitale'), ('nakuru', 'Nakuru'), ('thika', 'Thika Town'), ('nyeri', 'Nyeri'), ('nanyuki', 'Nanyuki'), ('naivasha', 'Naivasha'), ("murang'a", "Murang'a"), ('machakos', 'Machakos'), ('embu', 'Embu'), ('meru', 'Meru'), ('garissa', 'Garissa'), ('narok', 'Narok'), ('kericho', 'Kericho'), ('bomet', 'Bomet'), ('kisii', 'Kisii'), ('homa_bay', 'Homa Bay'), ('migori', 'Migori'), ('other', 'Other Location (Not Listed)')], db_index=True, help_text='Select your zone/neighborhood for accurate matching', max_length=50, validators=[core.choices.validate_location_choice]),
        ),
    ]
