# Generated by Django 5.2.5 on 2025-09-22 20:26

import core.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_donation_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='image',
            field=models.ImageField(blank=True, help_text='Photo of the food donation', null=True, upload_to=core.models.donation_image_path),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/default.png', null=True, upload_to=core.models.user_profile_picture_path),
        ),
        migrations.AlterField(
            model_name='donation',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 29, 20, 26, 35, 899797, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='donation',
            name='pickup_deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 24, 20, 26, 35, 900095, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='donation',
            name='pickup_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 23, 20, 26, 35, 899969, tzinfo=datetime.timezone.utc)),
        ),
    ]
