# Generated by Django 5.2.5 on 2025-12-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_emailverification_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='related_url',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
