# Generated by Django 5.2.5 on 2025-09-23 13:27

import core.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_donation_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='location_precision',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='donation',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 30, 13, 27, 25, 709272, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='donation',
            name='pickup_deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 25, 13, 27, 25, 709405, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='donation',
            name='pickup_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 24, 13, 27, 25, 709348, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.user_profile_picture_path),
        ),
    ]
