# Generated by Django 5.2.5 on 2025-12-03 16:13

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_userprofile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[core.validators.validate_phone_number]),
        ),
    ]
