# Generated by Django 5.2.5 on 2025-12-03 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_userprofile_phone_number'),
    ]

    operations = [
    ]
