# Generated by Django 5.2.5 on 2025-09-23 21:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_donation_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 30, 21, 1, 10, 384037, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='donation',
            name='pickup_deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 25, 21, 1, 10, 384161, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='donation',
            name='pickup_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 24, 21, 1, 10, 384099, tzinfo=datetime.timezone.utc)),
        ),
    ]
