# Generated by Django 5.2.5 on 2025-09-24 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_donation_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 1, 11, 31, 39, 60685, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='donation',
            name='pickup_deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 26, 11, 31, 39, 60923, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='donation',
            name='pickup_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 25, 11, 31, 39, 60837, tzinfo=datetime.timezone.utc)),
        ),
    ]
