# Generated by Django 5.2.5 on 2025-09-29 20:52

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_donation_expiry_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='dietary_tags',
            field=models.JSONField(blank=True, default=list, help_text='Dietary compatibility tags'),
        ),
        migrations.AddField(
            model_name='donation',
            name='estimated_calories',
            field=models.IntegerField(blank=True, help_text='Estimated total calories', null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='ingredients',
            field=models.TextField(blank=True, help_text='List of main ingredients'),
        ),
        migrations.AddField(
            model_name='donation',
            name='nutrition_score',
            field=models.IntegerField(default=0, help_text='Nutrition quality score (0-100)'),
        ),
        migrations.AddField(
            model_name='donation',
            name='preparation_method',
            field=models.CharField(blank=True, choices=[('raw', 'Raw'), ('cooked', 'Cooked'), ('baked', 'Baked'), ('fried', 'Fried'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='allergies',
            field=models.TextField(blank=True, help_text='List any food allergies (comma separated)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dietary_restrictions',
            field=models.JSONField(blank=True, default=list, help_text='List of dietary restrictions'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='health_notes',
            field=models.TextField(blank=True, help_text='Any additional health or nutrition notes'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nutrition_goals',
            field=models.CharField(choices=[('balanced', 'Balanced Diet'), ('weight_loss', 'Weight Loss'), ('muscle_gain', 'Muscle Gain'), ('maintenance', 'Maintenance'), ('health_condition', 'Specific Health Condition')], default='balanced', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_food_types',
            field=models.JSONField(blank=True, default=list, help_text='Preferred food categories'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 6, 20, 51, 2, 371165, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='donation',
            name='food_type',
            field=models.CharField(choices=[('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('dairy', 'Dairy'), ('bakery', 'Bakery'), ('cooked', 'Cooked Food'), ('grains', 'Grains & Cereals'), ('protein', 'Proteins'), ('beverages', 'Beverages'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='donation',
            name='pickup_deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 1, 20, 51, 2, 371276, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='donation',
            name='pickup_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 30, 20, 51, 2, 371235, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('donation_claimed', 'Donation Claimed'), ('donation_completed', 'Donation Completed'), ('new_donation', 'New Donation Available'), ('rating_received', 'New Rating Received'), ('dietary_match', 'Dietary Match Found'), ('nutrition_insight', 'Nutrition Insight'), ('system', 'System Notification')], max_length=20),
        ),
        migrations.CreateModel(
            name='NutritionImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('donations_made', models.IntegerField(default=0)),
                ('donations_received', models.IntegerField(default=0)),
                ('total_calories', models.IntegerField(default=0)),
                ('protein_grams', models.FloatField(default=0.0)),
                ('carbs_grams', models.FloatField(default=0.0)),
                ('fats_grams', models.FloatField(default=0.0)),
                ('fiber_grams', models.FloatField(default=0.0)),
                ('co2_saved_kg', models.FloatField(default=0.0)),
                ('water_saved_liters', models.FloatField(default=0.0)),
                ('food_waste_prevented_kg', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_impacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
