# Generated by Django 5.2.5 on 2025-10-12 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_donation_dietary_tags_donation_estimated_calories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 19, 14, 4, 40, 304166, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='donation',
            name='pickup_deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 14, 14, 4, 40, 304288, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='donation',
            name='pickup_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 13, 14, 4, 40, 304239, tzinfo=datetime.timezone.utc)),
        ),
    ]
